# Site settings
title: CS395T - Deep learning
email: philkr@cs.utexas.edu
description: "Course page and materials for UT Austin class CS395T - Deep learning"
baseurl: ""
url: "http://philkr.github.io/CS395T"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
