# Site settings
title: CS395T - Deep learning
email: philkr@cs.utexas.edu
description: "Course page and materials for UT Austin class CS395T - Deep learning"
url: "http://philkr.github.io/CS395T"
baseurl: /CS395T/

# Build settings
permalink: pretty
highlighter: rouge

markdown_ext: "md"
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge